### ISSUE TITLE
Feature request: queryGet.ASSOCIATIVE

### ISSUE THREAD

**Issue by benurb** [sagold/json-query#1]
Hi @sagold 😄 

Maybe you also think it might be a good idea to have a shortcut for the following use case:
```js
const result = {};
jsonQuery.run(this._data, pointer, (value, key, object, dataPointer) => {
    result[dataPointer] = value;
});
// result then is something like: { pointer1: data1, pointer2: data2, ... }
```

The shortcut would be:
```js
const result = jsonQuery.get(this._data, pointer, jsonQuery.get.ASSOCIATIVE);
```

What do you think?

Ben

**Comment by sagold** [comment]
Hi @benurb.

Yes. I Think this is a good idea. Spontaneously i would have implemented it as a separate method like in [jsonpointer.dict](https://github.com/manuelstofer/json-pointer#dictobject). Using the same name or something like _explode_ :). This stands against the interface of this repository, but it would be much simpler to use. What do you think?

**Comment by benurb** [comment]
Sounds good. I'll create a PR

**Comment by benurb** [comment]
Thank you!
